name: Pull Request Terraform Checks

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'terraform/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.8
      - name: Initialize Terraform modules
        run: terraform init
      - name: Validate Terraform
        run: terraform validate

  format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.8
      - name: Initialize Terraform modules
        run: terraform init
      - name: Check the Terraform format
        run: terraform fmt -recursive -check
